name: Micro CI Pipeline Test 1

variables:
  GO_ENV: development
  APP_VERSION: 1.0.0

jobs:
  - job: Micro CI Pipeline 1 Test Job
    image: golang:1.21-alpine
    variables:
      JOB_1_VAR: job1-tester
    steps:
      - name: Try Show Local Variable in another step
        script: |
          echo "Trying to access TEST_VAR from previous step: $TEST_VAR"
          echo "Job Variable JOB_1_VAR: $JOB_1_VAR"
          echo "Job Variable JOB_2_VAR: $JOB_2_VAR"

      - name: Failure Step Example
        continueOnError: true
        script: |
          echo "This pipeline should not exit due to a bash script failure
          asdfkjkqek ;k;kl

  - job: Second Job in Pipeline 1
    image: alpine:latest
    variables:
      JOB_2_VAR: job2-tester
    steps:
      - name: Show Local Variales and Environment Variables
        variables:
          TEST_VAR: tester
        script: |
          echo "This step is showing local variables and environment variables"
          echo "Job Variable JOB_1_VAR: $JOB_1_VAR"
          echo "Local Variable TEST_VAR: $TEST_VAR"
          echo "Environment Variable GO_ENV: $GO_ENV"
          echo "Environment Variable APP_VERSION: $APP_VERSION"